GET http://localhost:3310/api/damasparfum

############

POST http://localhost:3310/api/damasparfum HTTP/1.1
Content-Type: application/json

{
  "name": "Chanel No 5",
  "marque": "Chanel",
  "description": "Un parfum emblématique avec des notes florales et boisées.",
  "image": "https://example.com/chanel-no5.jpg",
  "user_id": "1"
  
}

###################
  

PUT http://localhost:3310/api/damasparfum/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Damas",
  "marque": "Damas",
  "description": "gqsrg",
  "image": "https://example.com/image.jpg",
  "user_id": "1"
}

